### ISSUE TITLE
Question - setup

### ISSUE THREAD

**Issue by gedw99** [dskinner/www#1]
This is really useful.
I was trying to get the let's encrypt working on appengine.

Any chance you could as some more setup / dependencies info to the readme.

Would like to try.

Also I found a go implementation for the client. It's called Lego :) by the same team and now part of caddy.

**Comment by dskinner** [comment]
Yeah, thanks for the ping. The cert expires in three months and it'd be nice to simplify/automate before I forget the little details.

I know the gcloud cli allows submitting ssl certs for GCE? But not sure about for use in appengine. Will need to read the docs a little more.

Itd also nice to respond to challenge auth without having to redeploy the app.

I found Lego a couple or so weeks back but then forgot the name and couldn't find bookmark. I'll check it out and see if it's of any use.
